//toFixed()
//A função toFixed() é usada para fixarmos um determinado número de casa decimais que desejamos mostrar...
let contaBancaria = 1.2848956; //Perceba que temos 7 casas decimais depois do ponto...
console.log(contaBancaria.toFixed(2)) //Usando a função reduzimos para mostrar só 2 casas decimais...