//toString()

//TRANSFORMANDO NUMBER EM STRING:
//A função toString() é usada para transformarmos um número em uma string, dessa forma...
let numero = 1000;
console.log("1) " + typeof numero.toString()); //Perceba que aquele número 1000 foi transformado em string...
console.log("2) " + typeof numero); //Mas veja que a função não transforma o tipo de dado da variável em number, ele transforma em string durante uma tacada só...


//TRANSFORMANDO NÚMERO EM BINÁRIO:
//Outra tarefa que é possível usando a função toString() é transformar um número em valor binário...
let bina = 11;
console.log("3) " + bina.toString(2)); //Perceba que o valor 11 foi passado como um valor binário, onde ele deixa de ser um number e passa a ser uma string binária...


//TRANSFORMANDO NÚMERO EM HEXADECIMAL:
//Outra tarefa que é possível usando a função toString() é transformar um número em valor hexadecimal...
let BB8 = 3000;
console.log("4) " + BB8.toString(16)); //Perceba que o valor 11 foi passado como um valor hexadecimal, onde ele deixa de ser um number e passa a ser uma string hexadecimal...