//charAt()
//É uma função que percorre uma string para achar um único caractere que esteja posicionado na posição índice passada como parâmetro de charAt():
console.log(("carrinho").charAt(4)); //Podemos usá-la colocando a String diretamente, seguido pela função...
let objeto = 'mesa';
console.log("O valor é: " + objeto.charAt(0)); //Podemos passá-la também por através de uma variável, veja o resultado para o índice 0...
console.log("O valor é: " + objeto.charAt(1)); //veja o resultado para o índice 1...
console.log("O valor é: " + objeto.charAt(2)); //veja o resultado para o índice 2...
console.log("O valor é: " + objeto.charAt(3)); //veja o resultado para o índice 3...


//OBSERVAÇÃO: a função charAt() não retorna erro se for colocado um valor índice que a string não o tenha...
console.log("O valor é: " + objeto.charAt(10)); //Perceba que é retornado uma string em vazio...