//charCodeAt():
//É uma função que traz para nós o valor Unicode ou ASCII do caractere correspondente ao valor índice passado como parâmetro:
let objeto = 'mesa';
console.log("O valor ASCII é: " + objeto.charCodeAt(1)); //O valor para a letra "e" é 101 em ASCII ou Unicode...
console.log('amor'.charCodeAt(0)); //Podemos passar a string diretamente também...