//split():
//FUNÇÃO QUE TRANSFORMA UMA STRING EM ARRAY Á PARTIR DE UM DETERMINADO CARACTERE:

console.log("Gabriel,Ferreira,Nobre".split(',')); //Aqui passamos a vírgula como delimitador...
console.log("Gabriel,Ferreira,Nobre".split('e')); //Aqui foi passado a letra "e"...
console.log("Gabriel,Ferreira,Nobre".split('i')); //Aqui foi passada a letra "i"...
console.log("Gabriel Ferreira Nobre".split(' ')); //Aqui foi passado o espaço em branco...