//pop():
//A função pop() é usada para quando desejamos retirar o último valor de um array e ainda por cima imprimir esse valor para que possamos visualizá-lo...

//RETIRANDO VALORES DO ARRAY E VISUALIZANDO O VALOR RETIRADO:
const VALORES = ['abacate', 'banana', 'maça', 'arroz'];

console.log(`1) ${VALORES.pop()}`); //Para isso usamos a função pop(), essa função retira o último valor do array e ainda imprime o valor que foi retirado...
console.log(`2) ${VALORES}`); //Note que o valor foi realmente retirado...