//IF:
//A estrutura if confere se uma condição foi satisfeita, caso a condição seja satisfeita ela executa o laço do if, caso não, ela ignora o laço...

//IF SÓ É INVOCADO SE A CONDIÇÃO FOR SATISFEITA:
function soBoaNoticia(nota) {
    if (nota >= 7) {
        console.log('1) Aprovado com ' + nota);
    }
}
soBoaNoticia(5); //Perceba que por não entrar no laço if nem imprime nada...
soBoaNoticia(8); //Esse caso já entra no laço if...



//EXEMPLOS DE UTILIZAÇÃO DE IF QUANDO UMA VARIÁVEL EQUIVALE A TRUE...
function soMostraSeForTrue(valor) {
    if (valor) { //no laço if se uma variável é colocada sozinha o if automáticamente analisa se ela tem um valor diferente de "undefined", "false", "0", "NaN" ou "null", se ela tiver qualquer valor diferente destes ela entra automáticamente no laço "if"...
        console.log('2) É verdade...', valor);
    }
}
console.log("\n");
//Os não encarados como true...
soMostraSeForTrue(); //Nenhum valor passado é null...
soMostraSeForTrue(null); //null não é impresso...
soMostraSeForTrue(undefined); //undefined não é impresso...
soMostraSeForTrue(NaN); //NaN não é mostrado...
soMostraSeForTrue(''); //String vazia não é mostrado...
soMostraSeForTrue(0); //0 equivale a false, então não é impresso...
//Os encarados como true...
soMostraSeForTrue(-1); //-1 é valor, então é mostrado...
soMostraSeForTrue(' '); //Uma string com espaço vazio é valor, então é mostrado...
soMostraSeForTrue('?'); //Qualquer caractere simbólico é valor, por isso é mostrado...
soMostraSeForTrue([]); //Um array sem nada é um array, por isso equivale a "true"...
soMostraSeForTrue([1, 2]); //Um array com valores obviamente é true, por isso é mostrado...
soMostraSeForTrue({}); //Um objeto mesmo que vazio é um objeto, por isso é mostrado...



//IF EXECUTA SOMENTE A PRÓXIMA SENTENÇA OU LINHA DEPOIS DA SUA DECLARAÇÃO, CASO NÃO ESTEJA SALVAGUARDADA PELAS CHAVES DO BLOCO:
function semBloco(num) {
    if (num > 7) //Perceba que não estamos usando os blocos aqui, e que a próxima sentença nem mesmo está na mesma linha do if, neste caso o if vai comentar a próxima linha ou sentença que aparecer, ignorando totalmente a segundo linha, mesmo que ela esteja identada dentro do if...
        console.log('3)', num);
        console.log('3) final');
}
console.log('\n');
semBloco(6); //Perceba que só "final" é impresso...
semBloco(8) //Perceba que tanto o número quando final são impresssos...