//FREEZE():
//O freeze() é uma função built-in do javascript que é utilizada para impedir que um objeto constante possa ter os valores de suas chaves - ou as próprias chaves - alteradas de alguma forma.
//Ele congela o elemento de tal forma que se torna impossível modificar seu conteúdo, nem mesmo sendo possível deletá-lo por através do comando "delete".
//OBS: o freeze() funciona somente com objetos, não importa se eles estão dentro de uma constante ou não.
//Veja como podemos utilizá-lo...

//POR QUE CONSEGUIMOS MUDAR OS VALORES DE OBJETOS MESMO ELES ESTANDO ARMAZENADOS EM CONSTANTES:
//Você deve ter percebido que, mesmo quando criamos objetos em constantes ainda assim é possível alterar os valores de suas chaves. Como no exemplo abaixo:
const pessoa = { nome: 'Gabriel', idade: '30'}
pessoa.nome = 'Graziela' //Veja que mudamos o nome apesar do objeto estar armazenado numa constante...
console.log(`\n1) ${pessoa.nome} ${pessoa.idade}`)

//isso acontece por que as constante guardam na verdade um endereço de memória, quando referenciamos ao objeto pessoa, ele na verdade é um endereço de memória que contém uma coleção de dados. Podemos mudar a coleção de dados se quisermos, mas não podemos mudar o endereço de memória jamais...
//****  DESCOMENTE AQUI PARA GERAR UM ERRO!!! pessoa = {nome: 'Gabriel'} //Perceba que temos um erro quando tentamos dar novos valores ao espaço de memória...



//CRIANDO CONSTANTES REALMENTE CONSTANTES:
//Podemos criar constantes que nunca poderão alterar suas chaves ou os valores delas usando um método built-in chamado "freeze()"...
const humano = Object.freeze({nome: 'Gabriel', idade: '30'}) //veja que freeze() deve ser utilizado sempre com conjunto com a função "Object", para que possamos criar um objeto que jamais poderá ser modificado...

humano.nome = 'Graziela' //Veja que embora tenhamos mudado o nome como no exemplo mais acima, com o freeze() o nome sempre será igual ao que foi declarado desde o ínicio...
console.log(`\n2) ${humano.nome} ${humano.idade}`)

delete humano.nome //Não podemos nem mesmo deletar nenhum valor...
console.log(`\n3)`, humano)
//O que for criado com freeze() só poderá ser deletado diretamente no código fonte...