//ASSIGN():
//A função built-in "assign()" é usada em objects para atribuir valores dinâmicamente á partir de outros objetos, com o assign é possível que o object capture os nomes das chaves os respectivos valores delas...
//OBS: Caso duas chaves tenham nomes iguais o valor da última chave irá sobrescrever o valor passado anteriormente...

const des = {a:1} 
const o1 = {b:2}
const o2 = {c:3, a: 4} //Veja que essa chave irá sobrescrever a chave "a" que está em "des"...

Object.assign(des, o1, o2) //o primeiro elemento passado será o responsável por receber as chaves e valores dos outros...
console.log(des) //Podemos chamar diretamente pelo nome do primeiro elemento...