//REVERSE():
//O reverse() é um método do tipo Array que pode ser usado para reverter os valores dos índices de um array, fazendo com que os valores dos índices finais sejam atribuídos aos valores dos índices á frente respectivamente...

//REVERTENDO VALORES DO ARRAY:
const arrayReverse = [1, 2, 3, 4, 5, 6]
console.log(arrayReverse.reverse()) //Note que o reverse faz o array retornar um valor invertido...