//PREVENTEXTENEXTENSIONS():
//A função preventExtensios() como o próprio nome diz prevê que as chaves de um objeto possam ser extendidas, podemos modificar os valores das chaves normalmente e podemos até deletar algumas chaves já existentes, mas nunca poderemos adicionar novas chaves. Podemos usá-la da seguinte forma...
const produto = Object.preventExtensions( //Note aqui que usamos a função no momento da inicialização do objeto, mas podemos usar depois do objeto estar inicializado também...
    {
        nome: 'Qualquer',
        preco: 1.99, 
        tag: 'promocao'
    } //O objeto não poderá receber chaves novas além dessas
    )

produto.nome = 'Borracha' //Veja que podemos mudar os valores...
produto.descricao = 'Essa é uma borracha que serve para apagar' //Mas não podemos adicionar novas chaves...
delete produto.tag //Mas podemos deletar chaves já existentes...
console.log('1)', produto)
