//FUNÇÃO SEAL() - SELANDO AS CHAVES DE UM OBJETO:
//A função seal() vai além da preventExtensions(), além de impedir que chaves novas possam ser criadas, a seal(), impede que as chaves possam ser deletadas também, porém os valores das chaves ainda poderão ser modificados normalmente...
const pessoa = {nome: 'Gabriel', idade: 30}
Object.seal(pessoa) //Aqui nós selamos o objeto "pessoa", suas chaves não poderão ser adicionadas e nem removidas...

pessoa.sobrenome = 'Ferreira' //Veja que uma chave nova não pôde ser adicionada...
delete pessoa.nome //A chave já existente não pôde ser removida...
pessoa.idade = 31 //O valor pôde ser alterado normalmente...
console.log('\n1)', pessoa)
