//FUNÇAO ISSEALED() - VERIFICANDO SE UM OBJETO ESTÁ SELADO OU NÃO:
//A função isSealed() verifica se um objeto foi selado ou não, se tiver sido selado ela retorna "true", se não tiver sido, ela retorna "false"...

const pessoa = {nome: 'Gabriel', idade: 30}
Object.seal(pessoa) //Aqui nós selamos o objeto "pessoa", suas chaves não poderão ser adicionadas e nem removidas...

pessoa.sobrenome = 'Ferreira' //Veja que uma chave nova não pôde ser adicionada...
delete pessoa.nome //A chave já existente não pôde ser removida...
pessoa.idade = 31 //O valor pôde ser alterado normalmente...
console.log('\n1)', pessoa)


console.log('\n2)', Object.isSealed(pessoa))