//DATE:
//"Date" é um função construtora do javascript para gerarmos datas nas nossas aplicações.
//Date trabalha com milissegundos á partir de janeiro de 1970, ele pode retorar esses milissegundos, ou pode retornar uma data segundo o padrão americano.

//INSTANCIANDO DATE:
const dataInstance = new Date() //Perceba que instanciamos Date...
console.log('1)', typeof dataInstance)



//INSTANCIANDO DATE E ATRIBUINDO VALORES DE FORMAS DIFERENTES:
const dateMilissegundos = new Date(7000000000000) //Veja que passando um valor em milissegundos ele irá retornar a data em milessegundos á partir de 01 de janeiro de 1970...
console.log('2)', dateMilissegundos)

const dateString = new Date('Octuber 30, 2021, 03:24:24') //Podemos passar a data como uma string seguindo o seguinte formato....
console.log('3)', dateString)

const dateString2 = new Date('2021-10-30T03:24:00') //Veja que ele recebe um valor string e retorna da mesma forma como um objeto instancia de date...
console.log('4)', dateString2, typeof dateString2)

const dateNumbers = new Date(2021, 10, 30) //Note um detalhe especial, os meses começam á partir do índice 0, portanto, se colocarmos 10, a referência será ao mês de novembro...
console.log('5)', dateNumbers) //Veja que será retornado no formato instanciado á Date...

const dateNumbersComplete = new Date(2021, 10, 30, 3, 24, 0) //Podemos também colocar a data completa colocando data e hora...
console.log('6)', dateNumbersComplete)



//MÉTODOS DE DATE:
//Date possuí métodos como:
//now(), que retorna o valor em milissegundos da presente data...
console.log('7)', Date.now(), Date(Date.now)) //Veja que usando o now() separadamente nós temos como retorno a data em milissegundos, e instanciando now() teremos como retorno a data de hoje completa...

//parse(), tranforma uma string passada como parâmetro para a data em milissegundos...
console.log('8)', Date.parse(2021-9-1), Date(1293840000000)) //Esses foram os últimos milissegundos capturados...

//getDate(), retorna somente o dia do mês de uma data especificada, se a data não tiver um determinado dia, ela retornará o dia correspondente ao número de dias decorridos á partir de determinada data...
console.log('9)', new Date(2021, 1, 28).getDate()) //Note que a data retornada é somente o dia...
console.log('10)', new Date(2021, 1, 35).getDate()) //Note que, como o dia 35 não existe em mês nenhum e fevereiro vai só até 28, ele avançou 7 dias á frente...