//GETDATE():
//O método "getDate()" é um método da função Date que retorna somente o dia da data, se a data não tiver um determinado dia, ela retornará o dia correspondente ao número de dias decorridos á partir de determinada data...

console.log('1)', new Date(2021, 1, 28).getDate()) //Note que a data retornada é somente o dia...
console.log('2)', new Date(2021, 1, 35).getDate()) //Note que, como o dia 35 não existe em mês nenhum e fevereiro vai só até 28, ele avançou 7 dias á frente...